### ISSUE TITLE
Manual epochs EXECUTION_LIMIT_REACHED

### ISSUE THREAD

**Issue by 0o-de-lally** [0LNetworkCommunity/libra-framework#182]
Manual epoch boundaries failing in prod on:
EXECUTION_LIMIT_REACHED

The global gas limit hits a limit on epoch boundary caltulations.
The limit is set in `0x1::GasScheduleV2::txn.maximum_number_of_gas_units`

The solution is to either bypass this check on the diem-node execution. Or increase the maximum gas allowed.

**Comment by 0o-de-lally** [comment]
@0xzoz here's an experimental fix which could apply in vendor code. https://github.com/0LNetworkCommunity/diem/blob/skip-gas-on-gov/diem-move/diem-vm/src/diem_vm.rs#L461

I think it's gross. But maybe the safest way.

**Comment by 0xzoz** [comment]
Closing due to the fix being implemented and merged [here](https://github.com/0LNetworkCommunity/diem/pull/2)
