### ISSUE TITLE
[feature] increase robustness of CI for framework upgrades

### ISSUE THREAD

**Issue by 0xzoz** [0LNetworkCommunity/libra-framework#183]
**Describe the Issue**  
The current CI pipeline does not dynamically replicate the production environment, particularly when dealing with upgrades involving the interdependent frameworks `move-stdlib` and `libra-framework`. This gap was highlighted during a recent upgrade attempt, where failure to upgrade `move-stdlib` before `libra-framework` led to errors (`MiscellaneousError(Some(LOOKUP_FAILED))` and `MiscellaneousError(Some(BACKWARD_INCOMPATIBLE_MODULE_UPDATE))`). This issue proposes enhancements to the CI process to build and test PR branches against the current main branch, ensuring a more accurate replication of the production environment and better dependency management.

**To Reproduce**
1. **Initial Upgrade Attempt**: The process began with an attempt to upgrade the `libra-framework` without first upgrading the `move-stdlib`. This initial step was based on the assumption that the existing version of `move-stdlib` on the VM was sufficient for the `libra-framework` upgrade.

2. **First Error Encountered**: This attempt resulted in an error, specifically a `MiscellaneousError(Some(LOOKUP_FAILED))`. The error indicated that the `libra-framework` upgrade failed because it required a function that was not available in the current version of `move-stdlib` running on the VM.

3. **Upgrading `move-stdlib`**: Following the error, the `move-stdlib` was then upgraded to address the missing function issue. This upgrade was necessary to provide the `libra-framework` with the required functionalities for its upgrade process.

4. **Second Upgrade Attempt**: With the `move-stdlib` now upgraded, a second attempt was made to upgrade the `libra-framework`. This step was expected to succeed, given that the previously missing function from `move-stdlib` should now be available.

5. **Second Error Encountered**: Despite the upgrade of `move-stdlib`, the second attempt to upgrade the `libra-framework` resulted in another error, this time a `MiscellaneousError(Some(BACKWARD_INCOMPATIBLE_MODULE_UPDATE))`. This error pointed to a backward compatibility issue with the module update, suggesting that the new version of `libra-framework` was not fully compatible with the existing system or other modules.

6. **Investigation and Analysis**: The errors encountered during the upgrade attempts prompted an investigation into the CI process and the upgrade procedure. This analysis highlighted the need for a more robust CI pipeline that could dynamically replicate the production environment to prevent such issues, specifically by ensuring that dependencies are upgraded in the correct sequence and are compatible with each other.

**Proposed Enhancements**
1. **Dynamic Environment Replication**: The CI pipeline should first build the software from the current main branch, representing the production environment. It should then build the software from the PR branch and use this build for testing upgrades. This approach ensures that the testing environment closely mimics the production setup.
2. **Dependency Management**: Introduce checks or a sequence in the CI process that ensures all dependencies (e.g., `move-stdlib`) are upgraded in the correct order before upgrading other components (e.g., `libra-framework`). This can prevent errors related to missing functions or backward compatibility issues.
3. **Enhanced Testing**: Specifically, the `tools/txs/upgrade_multiple.rs` test should be reviewed and possibly extended to cover these dynamic environment and dependency checks. This test should validate the upgrade process step-by-step, ensuring that each stage of the upgrade maintains compatibility and functionality.

**Expected Outcome**  
Implementing these enhancements will lead to a more robust CI process that can prevent upgrade-related errors by ensuring that:
- The testing environment accurately reflects the production setup.
- Dependencies are managed and upgraded in the correct sequence.
- Comprehensive testing validates the upgrade process, catching potential issues before deployment.

**Additional Context**  
The need for these enhancements was identified following recent upgrade attempts that highlighted the current CI pipeline's limitations. By addressing these issues, we aim to improve the reliability and stability of our software deployment process, ultimately leading to smoother upgrades and fewer production errors.

**Comment by 0o-de-lally** [comment]
@kalvkusk This is something to put in your backburner.
Re suggestion 1 Dynamic Environment Replication. We used to have a similar thing in v5 which did the following:
1. Starts a swarm/forge smoke test with the PROD version of the source.
2. switches branch to HEAD  Move source
3. builds upgrade payload
4. does governance upgrade in swarm
5. checks the network is alive.

This can be achieved by replicating our upgrade smoke tests (I think in tools/txs/tests). Currently those tests only check that upgrades by governance works by using HEAD source (then adding a Noop module to check upgrade happens).

**Comment by 0xzoz** [comment]
Closing. Addressed in #195
