### ISSUE TITLE
Remove transfer limit to new accounts and sunset onboarding entirely

### ISSUE THREAD

**Issue by siliconbits** [0LNetworkCommunity/libra-framework#243]
I propose the removal of the transfer limit for new accounts, a feature that presently introduces friction for both users and integrators.

This issue is highlighted by the recent closure of the onboarding channel in Discord, which asserts the bootstrapping phase being complete with the introduction of markets (and bridges) for new users to acquire coins and join the network. However, these platforms impose minimum withdrawal amounts that exceed the on-chain transfer limit to new accounts, thereby inhibiting users from taking custody of their coins on the native chain.

While it can be contended that integrators should refine their processes to accommodate this feature, the ultimate responsibility for validating and authorizing transactions lies with the user. Encouraging test transactions for significant value transfers is advisable and already a common practice within the industry, imposed limits and "onboarding" are arguably the foreign concepts.

Footnote to this would be to sunset onboarding entirely, i.e removing all onboarding terminology from documentation and wallet software too.

**Comment by 0o-de-lally** [comment]
Default transfer limit is a safety feature. A feature that was lost in the V7 update is the unlimited transfer function which experts and custodial accounts would use.
